---
AWSTemplateFormatVersion: 2010-09-09
Description: "AWS Autoremediation 2.0 target account template"
Metadata:
  AWS::CloudFormation::Interface:
    ParameterLabels:
      AWSManagementAccount:
        default: AWS Management Account ID

Parameters:
  AWSManagementAccount:
    Default: "998968464618"
    Description: 'AWS Account choosen for autoremediation management'
    Type: String

Resources:
  CIS14039VPCFlowLogsRole:
      Type: 'AWS::IAM::Role'
      Properties: 
        RoleName: !Sub "CIS-1-4-0-3-9-VPCFlowLogsRole_${AWS::Region}"
        Tags: 
          - Key: Type
            Value: !Sub "CIS-1-4-0-3-9-VPCFlowLogsRole_${AWS::Region}"
        AssumeRolePolicyDocument:
          Statement:
            - Effect: Allow
              Principal:
                Service: 
                  - vpc-flow-logs.amazonaws.com
              Action:
                - sts:AssumeRole

        Path: '/'
        Policies:
            - PolicyName: !Sub "CIS-1-4-0-3-9-VPCFlowLogsRole_${AWS::Region}"
              PolicyDocument:
                Statement:
                  - Effect: Allow
                    Action:
                      - "logs:CreateLogGroup"
                      - "logs:CreateLogStream"
                      - "logs:DescribeLogGroups"
                      - "logs:DescribeLogStreams"
                      - "logs:PutLogEvents"
                    Resource:
                      - "*"

  CIS14039VPCFlowLogsTargetRole:
      Type: 'AWS::IAM::Role'
      Properties: 
        RoleName: !Sub "CIS-1-4-0-3-9-VPCFlowLogsTargetRole_${AWS::Region}"
        Tags: 
          - Key: Type
            Value: !Sub "CIS-1-4-0-3-9-VPCFlowLogsTargetRole_${AWS::Region}"
        AssumeRolePolicyDocument:
          Statement:
            - Effect: Allow
              Principal:
                AWS: 
                  - "arn:aws:iam::415159976236:role/CIS-1-4-0-3-9-VPCFlowLogsLambdaRole_us-west-2"
              Action:
                - sts:AssumeRole

        Path: '/'
        Policies:
            - PolicyName: !Sub "CIS-1-4-0-3-9-VPCFlowLogsTargetPolicy_${AWS::Region}"
              PolicyDocument:
                Statement:
                  - Effect: Allow
                    Action:
                      - "ec2:CreateFlowLogs"
                      - "ec2:DescribeFlowLogs"
                      - "logs:CreateLogGroup"
                    Resource:
                      - !Sub "arn:aws:ec2:*:${AWS::AccountId}:vpc/*"
                      - !Sub "arn:aws:ec2:*:${AWS::AccountId}:vpc-flow-log/*"
                  - Effect: Allow
                    Action:
                      - "iam:PassRole"
                    Resource:
                      - !Sub "arn:aws:iam::${AWS::AccountId}:role/CIS-1-4-0-3-9-VPCFlowLogsRole_${AWS::Region}"

  


Outputs:
  CIS14039VPCFlowLogsRole:
    Value: !Ref CIS14039VPCFlowLogsRole
    Description: Roles to be used for the VPC Flow Logs delivery
  CIS14039VPCFlowLogsTargetRole:
    Value: !Ref CIS14039VPCFlowLogsTargetRole
    Description: VPC Flow Logs remediation role
  
