---
AWSTemplateFormatVersion: 2010-09-09
Description: "AWS Autoremediation 2.0 target account template"
Metadata:
  AWS::CloudFormation::Interface:
    ParameterLabels:
      AWSManagementAccount:
        default: AWS Management Account ID

Parameters:
  AWSManagementAccount:
    Default: ""
    Description: 'AWS Account choosen for autoremediation management'
    Type: String

Resources:
  CIS12039VPCFlowLogsRole:
      Type: 'AWS::IAM::Role'
      Properties: 
        RoleName: !Sub "CIS-1-2-0-2-9-VPCFlowLogsRole_${AWS::Region}"
        Tags: 
          - Key: Type
            Value: !Sub "CIS-1-2-0-2-9-VPCFlowLogsRole_${AWS::Region}"
        AssumeRolePolicyDocument:
          Version: "2012-10-17"
          Statement:
            - Effect: Allow
              Principal:
                Service: 
                  - vpc-flow-logs.amazonaws.com
              Action:
                - sts:AssumeRole

        Path: '/'
        Policies:
            - PolicyName: !Sub "CIS-1-2-0-2-9-VPCFlowLogsRole_${AWS::Region}"
              PolicyDocument:
                Version: "2012-10-17"
                Statement:
                  - Effect: Allow
                    Action:
                      - "logs:CreateLogGroup"
                      - "logs:CreateLogStream"
                      - "logs:DescribeLogGroups"
                      - "logs:DescribeLogStreams"
                      - "logs:PutLogEvents"
                    Resource:
                      - "*"

  CIS12039VPCFlowLogsTargetRole:
      Type: 'AWS::IAM::Role'
      Properties: 
        RoleName: !Sub "CIS-1-2-0-2-9-VPCFlowLogsTargetRole_${AWS::Region}"
        Tags: 
          - Key: Type
            Value: !Sub "CIS-1-2-0-2-9-VPCFlowLogsTargetRole_${AWS::Region}"
        AssumeRolePolicyDocument:
          Version: 2012-10-17
          Statement:
            - Effect: Allow
              Principal:
                AWS:
                  - !Sub >-
                    arn:aws:iam::${AWSManagementAccount}:role/CIS-1-2-0-2-9-VPCFlowLogsLambdaRole_${AWS::Region}
                Service:
                  - ssm.amazonaws.com
              Action:
                - 'sts:AssumeRole'

        Path: '/'
        Policies:
            - PolicyName: !Sub "CIS-1-2-0-2-9-VPCFlowLogsTargetPolicy_${AWS::Region}"
              PolicyDocument:
                Version: "2012-10-17"
                Statement:
                  - Effect: Allow
                    Action:
                      - "ec2:CreateFlowLogs"
                      - "logs:CreateLogGroup"
                    Resource:
                      - !Sub "arn:aws:ec2:*:${AWS::AccountId}:vpc/*"
                      - !Sub "arn:aws:ec2:*:${AWS::AccountId}:vpc-flow-log/*"
                      - !Sub "arn:aws:logs:*:${AWS::AccountId}:log-group:VPCFlowLogs/*"
                  - Effect: Allow
                    Action:
                      - "ec2:DescribeFlowLogs"
                    Resource:
                      - '*'
                  - Effect: Allow
                    Action:
                      - "iam:PassRole"
                    Resource:
                      - !Sub "arn:aws:iam::${AWS::AccountId}:role/CIS-1-2-0-2-9-VPCFlowLogsRole_${AWS::Region}"
                      
  CIS12041SecurityGroupsTargetRole:
      Type: 'AWS::IAM::Role'
      Properties: 
        RoleName: !Sub "CIS-1-2-0-4-1-SecurityGroupsTargetRole_${AWS::Region}"
        Tags: 
          - Key: Type
            Value: !Sub "CIS-1-2-0-4-1-SecurityGroupsTargetRole_${AWS::Region}"
        AssumeRolePolicyDocument:
          Version: "2012-10-17"
          Statement:
            - Effect: Allow
              Principal:
                AWS: 
                  - !Sub "arn:aws:iam::${AWSManagementAccount}:role/CIS-1-2-0-4-1-SecurityGroupsLambdaRole_${AWS::Region}"
              Action:
                - sts:AssumeRole

        Path: '/'
        Policies:
            - PolicyName: !Sub "CIS-1-2-0-4-1-SecurityGroupsTargetPolicy_${AWS::Region}"
              PolicyDocument:
                Version: "2012-10-17"
                Statement:
                  - Effect: Allow
                    Action:
                      - "ec2:DescribeSecurityGroupReferences"
                      - "ec2:DescribeSecurityGroups"
                      - "ec2:UpdateSecurityGroupRuleDescriptionsEgress"
                      - "ec2:UpdateSecurityGroupRuleDescriptionsIngress"
                      - "ec2:RevokeSecurityGroupIngress"
                      - "ec2:RevokeSecurityGroupEgress"
                    Resource:
                      - '*'
                  - Effect: Allow
                    Action:
                      - "ssm:StartAutomationExecution"
                    Resource:
                      - !Sub "arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:document/AWS-DisablePublicAccessForSecurityGroup"
                      - !Sub "arn:aws:ssm:${AWS::Region}:*:automation-definition/*"
                  - Effect: Allow
                    Action:
                      - "iam:PassRole"
                    Resource:
                      - !Sub "arn:aws:iam::${AWS::AccountId}:role/CIS-1-2-0-4-1-SecurityGroupsTargetRole_${AWS::Region}"

  S3DLPLabelActionTargetRole:
      Type: 'AWS::IAM::Role'
      Properties: 
        RoleName: !Sub "S3DLPLabelActionTargetRole_${AWS::Region}"
        Tags: 
          - Key: Type
            Value: !Sub "S3DLPLabelActionTargetRole_${AWS::Region}"
        AssumeRolePolicyDocument:
          Version: 2012-10-17
          Statement:
            - Effect: Allow
              Principal:
                AWS: 
                  - !Sub "arn:aws:iam::${AWSManagementAccount}:role/S3DLPLabelActionLambdaRole_${AWS::Region}"
              Action:
                - 'sts:AssumeRole'
        Path: '/'
        Policies:
            - PolicyName: !Sub "S3DLPLabelActionTargetRole_${AWS::Region}"
              PolicyDocument:
                Version: "2012-10-17"
                Statement:
                  - Effect: Allow
                    Action:
                      - 's3:GetBucketTagging'
                      - 's3:PutBucketTagging'
                      - 's3:GetObjectTagging'
                      - 's3:PutObjectTagging'
                    Resource:
                      - '*'


Outputs:
  CIS12039VPCFlowLogsRole:
    Value: !Ref CIS12039VPCFlowLogsRole
    Description: Roles to be used for the VPC Flow Logs delivery
  CIS12039VPCFlowLogsTargetRole:
    Value: !Ref CIS12039VPCFlowLogsTargetRole
    Description: VPC Flow Logs remediation role
  CIS12041SecurityGroupsTargetRole:
    Value: !Ref CIS12041SecurityGroupsTargetRole
    Description: Roles to be used for the Security Group remediation
  S3DLPLabelActionTargetRole:
    Value: !Ref S3DLPLabelActionTargetRole
    Description: Roles to be used for the S3 DLP Label Action
  
