---
AWSTemplateFormatVersion: 2010-09-09
Description: "AWS Autoremediation 2.0 target account template"
Metadata:
  AWS::CloudFormation::Interface:
    ParameterLabels:
      AWSManagementAccount:
        default: AWS Management Account ID

Parameters:
  AWSManagementAccount:
    Default: ""
    Description: 'AWS Account choosen for autoremediation management'
    Type: String

Resources:
  CIS12041SecurityGroupsPort22TargetRole:
      Type: 'AWS::IAM::Role'
      Properties: 
        RoleName: !Sub "CIS-1-2-0-4-1-VecurityGroupsPort22TargetRole_${AWS::Region}"
        Tags: 
          - Key: Type
            Value: !Sub "CIS-1-2-0-4-1-VecurityGroupsPort22TargetRole_${AWS::Region}"
        AssumeRolePolicyDocument:
          Version: "2012-10-17"
          Statement:
            - Effect: Allow
              Principal:
                AWS: 
                  - !Sub "arn:aws:iam::${AWSManagementAccount}:role/CIS-1-2-0-4-1-SecurityGroupsPort22LambdaRole_${AWS::Region}"
              Action:
                - sts:AssumeRole

        Path: '/'
        Policies:
            - PolicyName: !Sub "CIS-1-2-0-4-1-VecurityGroupsPort22TargetPolicy_${AWS::Region}"
              PolicyDocument:
                Version: "2012-10-17"
                Statement:
                  - Effect: Allow
                    Action:
                      - "ec2:DescribeSecurityGroupReferences"
                      - "ec2:DescribeSecurityGroups"
                      - "ec2:UpdateSecurityGroupRuleDescriptionsEgress"
                      - "ec2:UpdateSecurityGroupRuleDescriptionsIngress"
                      - "ec2:RevokeSecurityGroupIngress"
                      - "ec2:RevokeSecurityGroupEgress"
                    Resource:
                      - '*'
                  - Effect: Allow
                    Action:
                      - "ssm:StartAutomationExecution"
                    Resource:
                      - !Sub "arn:aws:ssm:{AWS::Region}:${AWS::AccountId}:document/AWS-DisablePublicAccessForSecurityGroup"
                      - !Sub "arn:aws:ssm:{AWS::Region}:*:automation-definition/*"
                  - Effect: Allow
                    Action:
                      - "iam:PassRole"
                    Resource:
                      - !Sub "arn:aws:iam::${AWS::AccountId}:role/CIS-1-2-0-4-1-VecurityGroupsPort22TargetPolicy_${AWS::Region}"